// Revly — Single source of truth for FAQ data (reused for rendered FAQ sections and structured data)

export const HOME_FAQ = [
{ q: "Is this just AI generating fake reviews?", a: "No. The customer writes their own review. They can use our AI to help draft it and add detail, but it doesn't replace what they said. The customer reads it, edits it if they want to, and posts it themselves. Their voice, their specific points, their approval." },
{ q: "What platforms does Revly work with?", a: "Revly currently supports G2, Capterra, GetApp, Software Advice, Trustpilot, Apple App Store, Google PlayStore, Shopify App Store, WooCommerce Marketplace, QuickBooks Marketplace, WordPress Plugin Marketplace, Xero Marketplace. More platforms are being added. If a platform matters for software buying decisions, it's on the roadmap." },
{ q: "How is this different from emailing customers and asking for a review?", a: "When you email customers manually, you're guessing who's happy, sending links to multiple platforms and hoping they pick the right one, and getting back whatever they feel like writing. Revly replaces all three steps: sentiment screening identifies who to ask for a public review and who to send to your support team; a smart link routes them to the right platform based on your goals; AI drafting turns their response into a review that's actually useful to someone evaluating your product." },
{ q: "What if a customer doesn't want to post the AI-drafted review?", a: "They can edit it, rewrite it entirely, or decline. Nothing goes live without their explicit approval. If they don't post, nothing happens. No chasing, no pressure." },
{ q: "How long does setup take?", a: "Under 30 minutes for most teams. Connect your review platforms, create your first smart review link, and send your first campaign. Most customers see their first reviews come in within a few days." },
{ q: "Is Revly right for a company with only a handful of reviews?", a: "Yes, that's a common starting point. Companies with 10–50 reviews have enough customers to run meaningful campaigns, but not enough reviews to have social proof that converts. Getting from thin to credible is the first thing Revly helps with." }];

export const PRICING_FAQ = [
  { q:"What happens when I hit my review limit?", a:"Collected reviews reset each month. If you hit your limit, new collection links pause until next month. Monitoring continues uninterrupted." },
  { q:"Can I add extra channels?", a:"Yes! Pro plans can add channels for $5/mo each, Business and Agency for $3/mo each." },
  { q:"What platforms do you monitor?", a:"Shopify App Store, G2, QuickBooks App Store, WordPress.org, Xero App Store, WooCommerce Marketplace, and Capterra. More coming soon." },
  { q:"How does AI review enhancement work?", a:"Customers share a quick star rating and a few words of feedback. Our AI expands this into a complete, authentic review that matches their sentiment and tone, ready to copy and post on any platform." },
  { q:"Can I switch plans?", a:"Yes, upgrade or downgrade anytime. Changes take effect immediately, and we prorate the difference." },
  { q:"Do you offer a free trial of paid plans?", a:"The Free plan lets you try core features. When you're ready, upgrade to Pro or Business. No trial needed, cancel anytime." },
];

export const COLLECT_FAQ = [
  { q: "How do you collect better reviews on G2, Capterra, and other software platforms?", a: "The most common barrier to useful reviews is friction. Customers don't know what to write or which platform to use. Revly removes both by providing one smart link that handles platform routing automatically, and AI writing assistance that helps customers turn a brief thought into a detailed, specific review. The result is more reviews, on the right platforms, that actually reflect what customers think." },
  { q: "Is the AI writing the review for the customer?", a: "No. The customer writes their review first, in their own words. If they want help expanding or structuring what they've written, Revly's AI offers suggestions, but the customer can edit, rewrite, or ignore the suggestions entirely. Nothing goes live without their explicit approval. The AI assists; it doesn't replace." },
  { q: "What if the customer just wants to write their own review without AI help?", a: "That's completely fine. The AI assistance is optional. Customers who want to write their own review from scratch can do so. Revly just makes sure they end up on the right platform without having to choose between multiple links." },
  { q: "How does the smart routing work?", a: "You set the routing priority in Revly. If you need more reviews on a specific platform (say G2 is strong but Capterra is thin), you can prioritise Capterra until it's balanced. Or you can let Revly distribute automatically based on your current review counts across platforms. Either way, customers get sent to one place with no confusion about where to go." },
  { q: "Can customers leave a review on the platform they prefer?", a: "The smart link routes customers based on your priorities, but the goal is always to remove confusion rather than force a choice. If a customer has a strong preference for a specific platform, they can still post there directly. Revly just ensures the default is wherever you need reviews most." },
  { q: "What kinds of reviews does this produce?", a: "Reviews that are more detailed and specific than what customers typically write without assistance. Instead of \"Great tool, easy to use\" (which tells a prospect nothing), customers are more likely to describe the specific problem it solved, the feature that made the difference, or how it compares to what they used before. That's the information that actually influences buying decisions." },
  { q: "Does this work if we only have a small number of customers?", a: "Yes, in fact it matters more. With a small customer base, every review counts more. Revly makes sure each one lands on the right platform and says something useful. One well-written review on the right platform does more than five vague ones spread across platforms you're not actively trying to build." }];

export const MONITOR_FAQ = [
  { q: "How do you monitor across G2, Capterra, and Trustpilot without logging into each?", a: "Revly connects to each platform once during setup and syncs every new review into one dashboard automatically. After connection, you never need to log into the individual platforms to check or read reviews. Everything appears in your Revly feed within five minutes of being posted." },
  { q: "Which platforms does Revly monitor?", a: "Revly currently monitors G2, Capterra, GetApp, Software Advice, Trustpilot, Apple App Store, Google Play Store, Shopify App Store, WooCommerce Marketplace, QuickBooks Marketplace, WordPress Plugin Marketplace, and Xero Marketplace. More platforms are added regularly. If a platform matters for software buying decisions, it's on the roadmap." },
  { q: "How quickly does Revly pick up new reviews?", a: "New reviews appear in your Revly dashboard within five minutes of being posted on the source platform. You don't have to refresh, check, or log in anywhere to see them." },
  { q: "Can I search for specific quotes or topics?", a: "Yes. Your entire review history is searchable from one place. Search by keyword, feature name, customer language, or topic to find the exact quote you need for a campaign, landing page, or sales conversation." },
  { q: "Does Revly notify me when a new review comes in?", a: "Yes. You can configure notifications via email and Slack, so the right person on your team is alerted as soon as a new review is posted on any connected platform." },
  { q: "How is this different from checking each platform manually?", a: "Manual checking is reactive. You remember to look, or you don't. Reviews go unread for days or weeks. Trends are invisible because you only see one platform at a time. Revly replaces that with a single feed updated every five minutes, so nothing slips through and patterns become visible across platforms." }];

export const SMART_FAQ = [
  { q: "Why check in with customers before sending them to a review platform?", a: "Sending a public review request without knowing how a customer feels is a coin flip. Some land on a platform when they would have benefited from support first. A short feedback step turns one campaign into two distinct, useful workflows: customers who are ready share publicly, and customers who need help reach your team. Both outcomes are better than the alternative." },
  { q: "What does the feedback step look like for the customer?", a: "It's a short check-in, usually a question or two, that takes seconds to complete. Customers don't see it as a survey or a barrier; it feels like part of the review flow. Their answers determine where they go next, automatically." },
  { q: "What happens to customers who indicate they need support?", a: "They share more detail with your team via a short form, and your team gets notified. The customer never lands on a public review platform from this flow. Instead, they get the chance to flag whatever's wrong and have you address it." },
  { q: "Is this hiding negative reviews?", a: "No. Customers can still leave a public review independently if they choose. What Revly does is route the review request itself, so a customer who would benefit from support gets help instead of a request to post publicly at the wrong moment. The customer decides whether to post anywhere, always." },
  { q: "How does the routing decide where to send a customer?", a: "You configure the rules in Revly. Based on what the customer shares in the feedback step, Revly routes them either to the review platform you want to prioritise, or to the private feedback path that reaches your team." },
  { q: "Will customers know they're being filtered?", a: "No. The feedback step looks like a natural first part of the review flow. It asks how things are going. Customers who are happy proceed to a review platform; customers who flagged an issue proceed to a form for your team. Both paths feel coherent and intentional." },
  { q: "How is this different from a Net Promoter Score survey?", a: "NPS is a measurement tool. It asks how likely you are to recommend, then tracks the score. Revly's feedback step is operational. It routes each customer based on their response, in real time, to the action that fits their experience. You're not just measuring sentiment; you're acting on it." },
  { q: "Can I run this on customers I don't know personally?", a: "Yes, that's the most common use case. The feedback step is automated, so it works whether you have ten customers or ten thousand. Each customer gets the right next step based on their own response, regardless of how well your team knows them individually." }];

export const RESPOND_FAQ = [
  { q: "How do you respond to reviews on G2, Capterra, and other software platforms from one place?", a: "Revly pulls every review from your connected platforms into one dashboard. You filter to unresponded reviews and draft a reply with AI in your brand voice. Then, Revly takes you directly to the review source platform to post it. No logging into each platform separately, no searching for the review again." },
  { q: "Can the AI match my brand voice?", a: "Yes. You set up tone instructions in Revly's settings: formal vs casual, sign-off conventions, words to use or avoid. Revly's AI uses those instructions to draft replies that sound like your team from the first draft, not generic responses you have to rewrite." },
  { q: "Why does it matter to respond to positive reviews too?", a: "Responding to positive reviews acknowledges the customers who took the time to advocate for you, and it signals to prospects browsing your profile that you actually engage. It also adds indexable content on review platforms that AI systems and search engines cite. Your responses become part of how your product is described publicly." },
  { q: "Will Revly post the response automatically?", a: "No. Revly drafts the response and takes you directly to the review on the platform, but you post it yourself. This keeps the response under your team's control and ensures every reply is a deliberate decision, not an automated one." },
  { q: "How does responding to reviews help with AEO and SEO?", a: "Review platforms like G2 and Capterra are among the most cited domains in AI-generated answers for commercial queries. Responses that mirror the language of the review (feature names, outcomes, specific use cases) add indexable content on those high-authority domains and reinforce what your product does and who it's for." },
  { q: "What happens if a critical review needs urgent attention?", a: "You can configure notifications via email or Slack so the right person on your team is alerted as soon as a low-rated review is posted. Filter your dashboard to unresponded critical reviews and address them while the customer is still listening." },
  { q: "Can multiple team members manage responses?", a: "Yes, with all Revly paid plans. Multiple team members can be added, each with their own access. You can see who drafted or posted which response, and assign reviews to the right person on your team." },
  { q: "How long does it take to draft a response in Revly?", a: "Drafting takes seconds. The AI generates a reply matched to your brand voice based on the review content. You edit if you want to, then click through to post on the platform. Most teams find responding goes from a chore they avoid to something they actually keep up with." }];

export const SAAS_FAQ = [
  { q: "Does Revly post reviews on my behalf?", a: "No. Revly helps customers write better reviews, but the customer always approves the final text before posting it themselves. You are never posting on someone else's behalf." },
  { q: "Why does Revly check in with customers before a review request?", a: "Revly runs a short check-in before directing any customer to a public review platform. Their response determines the next step: a guided path to the right platform, or a private form that reaches your team. Customers who get help when they need it are far more likely to become genuine advocates." },
  { q: "Which platforms does Revly support?", a: "Revly currently supports G2, Capterra, Shopify App Store, QuickBooks App Store, Xero App Store, WooCommerce, and WordPress.org, with more platforms being added." },
  { q: "Is this suitable for a solo marketer with no review operations process in place?", a: "Yes. Revly is built for exactly this situation. Setup takes under 30 minutes and the system handles the operational side so you do not need a dedicated process to get started." }];

export const AGENCY_FAQ = [
  { q: "Can I manage multiple clients from a single Revly account?", a: "Yes. Revly's dashboard is designed to handle multiple products and client accounts from one login. You can switch between clients instantly and see aggregate performance across all of them." },
  { q: "Does Revly offer white-label options for agencies?", a: "White-label functionality is on the Revly roadmap. Get in touch to discuss options and early access." },
  { q: "Which review platforms does Revly support?", a: "Revly currently supports G2, Capterra, Shopify App Store, QuickBooks App Store, Xero App Store, WooCommerce, and WordPress.org, with more platforms being added." },
  { q: "How does the check-in work for client campaigns?", a: "Every Revly collection campaign includes a built-in check-in. Each customer's response determines where they go next: the platform where a review is needed most, or a private form that reaches your client's team. That early signal gives your client the chance to step in, help, and turn the experience around." }];
